# Generated by Django 5.2.7 on 2025-10-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Введите полное имя сотрудника', max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(help_text='Введите должность сотрудника', max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название задачи', max_length=255, verbose_name='Наименование')),
                ('due_date', models.DateField(help_text='Дата окончания задачи', verbose_name='Срок')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Выполнена')], default='pending', max_length=20, verbose_name='Статус')),
                ('assignee', models.ForeignKey(blank=True, help_text='Сотрудник, которому назначена задача', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee', verbose_name='Исполнитель')),
                ('parent_task', models.ForeignKey(blank=True, help_text='Задача, от которой зависит текущая', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.task', verbose_name='Родительская задача')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
